name: Test Action

on: [ push ]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Step_1
        uses: ./ # Uses an action in the root directory
        id: test
        with:
          other-repo-name: OSKAR
          other-repo-owner: OxfordSKA
      - name: Step_2
        run: |
          echo $steps.Step_1.test.outputs.tags

  job_2:
    # this means, wait for the "provide_packages_json" phase 1 to finish
    needs: job_1

    runs-on: ubuntu-latest
    strategy:
      # â†“ the real magic happens here - create dynamic matrix from the json
      matrix:
        tag: ${{ fromJson(needs.job_1.Step_1.test.outputs.tags) }}

    steps:
      - name: Step0
        run: |
          echo from ${{ matrix.tag }}
